### ISSUE TITLE
netstandard1.6 gone from 0.3.23

### ISSUE THREAD

**Issue by haf-lynx** [Hopac/Hopac#131] opened 2016-10-04 07:30 UTC
It would seem the v0.3.23 release is broken in that it's missing both Platform and NetStandard libs.

**Comment by polytypic** [comment] 2016-10-04 08:46
Hmm... I can't reproduce the problem.

After `rm -rf ~/.nuget` and then successfully installing and building a couple of Hopac projects:

```
$ unzip -l ~/.nuget/packages/Hopac/0.3.23/Hopac.0.3.23.nupkg
Archive:  /Users/vesakarv/.nuget/packages/Hopac/0.3.23/Hopac.0.3.23.nupkg
  Length     Date   Time    Name
 --------    ----   ----    ----
      603  09-30-16 21:15   [Content_Types].xml
      471  09-30-16 21:15   _rels/.rels
     1519  09-30-16 21:18   Hopac.nuspec
    62976  09-30-16 18:14   lib/net45/Hopac.Core.dll
    30177  09-30-16 18:14   lib/net45/Hopac.Core.dll.mdb
    25054  09-30-16 18:14   lib/net45/Hopac.Core.xml
   649216  09-30-16 18:15   lib/net45/Hopac.dll
    86776  09-30-16 18:15   lib/net45/Hopac.dll.mdb
     7680  09-30-16 18:15   lib/net45/Hopac.Platform.dll
      660  09-30-16 18:15   lib/net45/Hopac.Platform.dll.mdb
   143180  09-30-16 18:14   lib/net45/Hopac.xml
    57856  09-30-16 21:18   lib/netstandard1.6/Hopac.Core.dll
    24149  09-30-16 21:18   lib/netstandard1.6/Hopac.Core.xml
   643584  09-30-16 21:18   lib/netstandard1.6/Hopac.dll
     8704  09-30-16 21:18   lib/netstandard1.6/Hopac.Platform.dll
      122  09-30-16 21:18   lib/netstandard1.6/Hopac.Platform.xml
   143048  09-30-16 21:18   lib/netstandard1.6/Hopac.xml
      821  09-30-16 21:15   package/services/metadata/core-properties/coreProp.psmdcp
 --------                   -------
  1886596                   18 files
```

**Comment by polytypic** [comment] 2016-10-04 09:04
This must be due to changes in implementation details exposed due to inlining. Not sure which version actually had the binary breaking changes. Recompile should fix that. In the future the version number should be updated to reflect binary incompatible changes.

**Comment by haf** [comment] 2016-11-05 18:13
Ok, closing for now; reopening if this issue rears its head again.

**Closed by haf** 2016-11-05 18:13 UTC
