### ISSUE TITLE
Broken intellisense w/ Xamarin Studio

### ISSUE THREAD

**Issue by pmarks** [Hopac/Hopac#59] opened 2015-03-10 02:17 UTC
I'm getting broken Intellisense from Hopac on Xamarin Studio:
![screen shot 2015-03-09 at 6 55 42 pm](https://cloud.githubusercontent.com/assets/45827/6568005/f51beb46-c68d-11e4-91ba-c4d6a5e24bd9.png)

This occurs when using the current NuGet binaries (0.0.0.44) or using Hopac from source (current master). I'm using Xamarin Studio 5.7.2 (latest stable) on OSX 10.9.

Prior to this commit, I'm able to get full Intellisense from Xamarin Studio, which makes for a very nice experience: https://github.com/Hopac/Hopac/commit/bbe862ff5aab8942e9ff867f6d0ecdfc2bf5dd57

I'm wondering if there's anything that can be done to the build settings to make the library play nice with Xamarin Studio?  I'm willing to spend some time to help find a resolution if you have any suggestions here.

**Comment by VesaKarvonen** [comment] 2015-03-11 05:54
Hmm... I can reproduce this issue by creating a new project with Xamarin.  However, interestingly, if I open a project with Xamarin that has been initially created (and updated) using VS, I see the documentation as usual.

**Comment by VesaKarvonen** [comment] 2015-03-11 18:42
This problem seems to be related to PCL profiles.  Adding a reference to the System.Runtime.dll as described in http://www.knowing.net/index.php/2014/08/27/xamarin-forms-programming-in-f/ eliminates the error message, but the documentation is still not available.

I'm afraid I don't know enough about PCL and Xamarin to fix this problem right now.

**Comment by haf** [comment] 2015-05-23 11:05
So now that you've removed PCL this should be fixed.

**Comment by VesaKarvonen** [comment] 2015-05-23 11:23
Like @haf commented this is now "fixed".  However, what I'd really like is to have the PCL profiles working so that the library would just work on multiple platforms.  Contributions are welcome. :)

**Closed by VesaKarvonen** 2015-05-23 11:23 UTC

**Comment by dsyme** [comment] 2015-05-30 08:21
In F# 4.0 F# Interactive (fsi.exe) will reference System.Runtime by default.  Just to check that this will this solve this problem?
