### ISSUE TITLE
Why does the left side not uncommit after the right side has been chosen when using Alt.prepare?

### ISSUE THREAD

**Issue by mrakgr** [Hopac/Hopac#206] opened 2020-11-13 10:50 UTC
```fs
open Hopac
open Hopac.Infixes

let req = Ch()
let rec waiting c : unit Alt = req ^=> processing c
and processing c () : unit Alt = waiting c <|> Alt.prepare(Job.thunk (fun () ->
    printfn "%i" c
    waiting (c+1)
    ))

Hopac.start (waiting 0)

let x =
    req *<+ () >>=.
    timeOutMillis 100 >>=.
    req *<+ ()

Hopac.run x
System.Console.ReadKey()
```

The above for me prints two `0`s when I'd expect it to print `0` and `1`. Why is this happening? Is this a library bug?

**Comment by mrakgr** [comment] 2020-11-13 11:16
```fs
open Hopac
open Hopac.Infixes

let req = Ch()
let rec waiting c : unit Alt = req ^=> processing c
and processing c () : unit Alt = 
    waiting c <|> (Alt.unit() ^=> fun () ->
        printfn "%i" c
        waiting (c+1)
        )

Hopac.start (waiting 0)

let f = req *<+ () >>=. timeOutMillis 100
Hopac.run (f >>=. f)
    
System.Console.ReadKey()
```

I just discovered that this example works as one would expect. So the only thing I can infer is that `Alt.prepare` does something quite different than I would anticipate. What should I be using it for?

Note that these are simplified examples. As a background, I actually encountered an issue because of this behavior because cancellation tokens would get filled twice. This is even more surprising because apart from that, I used a similar `Alt.prepare` pattern in the past and now I am wondering whether there are bugs lingering in my past code. I'll have to go over it in order to make sure.

**Comment by haf** [comment] 2020-11-15 13:15
Alt.prepare doesn't commit itself. It returns an Alt that can, allowing you to pre-compute that Alt's inputs. In your example, you have two Alts waiting for `req` to receive a signal, one of them will commit, and in your first example you immediately recurse with `c=0`. Also `<|>` picks the first Alt, always, if both are available at the same instant.

So I'm not sure what's wrong here.

**Comment by haf** [comment] 2020-11-15 13:18
Closing as not a bug, works as intended.

**Closed by haf** 2020-11-15 13:18 UTC

**Comment by mrakgr** [comment] 2020-11-15 13:32
So you are saying that...

```fs
    waiting c <|> (Alt.unit() ^=> fun () ->
        printfn "%i" c
        waiting (c+1)
        )
```

...reduces to...

```fs
    waiting c <|> waiting (c+1)
```

...and the left side always gets picked?

**Comment by haf** [comment] 2020-11-15 21:18
LHS

waiting c
block on req

RHS

Alt.unit
Alt.afterJob commits to Alt.unit

LHS

cancelled from RHS committing

RHS

print c
recurse

---


So no, it doesn't reduce to that, exactly. Your reduction would commit RHS, but Alt.unit causes afterJob to commit in your actual code.

**Comment by mrakgr** [comment] 2020-11-15 22:55
Sorry, I made a dumb mistake. I pasted the wrong thing as the first example.

```fs
waiting c <|> Alt.prepare(Job.thunk (fun () ->
    printfn "%i" c
    waiting (c+1)
    ))
```

I meant to ask whether the above reduces to...

```fs
    waiting c <|> waiting (c+1)
```

**Comment by haf** [comment] 2020-11-16 08:47
Yes

**Comment by mrakgr** [comment] 2020-11-16 09:54
Thank you for clearing that up.
